#!/bin/bash

# delete if already exists
rm Turbine.msh
# gmsh can't be run in docker container
/Applications/Gmsh.app/Contents/MacOS/gmsh ./TODOFILENAME -3 -smooth 2 -clmax .25 -o ./Turbine.msh
# for mac only
echo '$End' >> Turbine.msh
